version: 0.2

environment_variables:
  plaintext:
    NS_ENV: "ci"

phases:
  build:
    commands:
      # Test Carbon
      - . /root/.bashrc && nvm use 8
      - npm install
      - npm run lint
      - npm run test
      # Test Boron
      - . /root/.bashrc && nvm use 6
      - npm install
      - npm run lint
      - npm run test
      # Test Argon
      - . /root/.bashrc && nvm use 4
      - npm install
      - npm run lint
      - npm run test
